/*  Vector field and other functions for Auto continuer.
   This code was automatically generated by PyDSTool, but may be modified by hand. */

#include "auto_f2c.h"
#include <stdio.h>
#include "autovfield.h"
#include <math.h>
#include "auto_c.h"
#include <string.h>
#include <stdlib.h>

double *gICs;
double **gBds;
double globalt0;

static double pi = 3.1415926535897931;


/* Variable, parameter, and input definitions: */ 
#define I	p_[0]
#define Vo	p_[1]
#define a	p_[2]
#define b	p_[3]
#define c	p_[4]
#define d	p_[5]
#define g	p_[6]
#define lam	p_[7]
#define r	p_[8]
#define s	p_[9]
#define thet	p_[50]
#define x1	p_[51]
#define _T	p_[10]
#define x	Y_[0]
#define y	Y_[1]
#define z	Y_[2]


int getindex(char *name, double *p_, double *wk_, double *xv_);
double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double globalindepvar(double t, double *p_, double *wk_, double *xv_);
double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_);
double initcond(char *varname, double *p_, double *wk_, double *xv_);
int heav(double x_, double *p_, double *wk_, double *xv_);
double gam(double __x__, double *p_, double *wk_, double *xv_);
double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);

void auxvars(unsigned, unsigned, double, double*, double*, double*, unsigned, double*, unsigned, double*);
void jacobian(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
void jacobianParam(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
int N_AUXVARS = 0;


void vfieldfunc(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){

f_[0] = y-a*x*x*x+b*x*x+I-z-g*(x-Vo)*gam(x, p_, wk_, xv_);
f_[1] = c-d*x*x-y;
f_[2] = r*(s*(x-x1)-z);

}




int getindex(char *name, double *p_, double *wk_, double *xv_) {

  if (strcmp(name, "x")==0)
	return 0;
  else if (strcmp(name, "y")==0)
	return 1;
  else if (strcmp(name, "z")==0)
	return 2;
  else if (strcmp(name, "I")==0)
	return 3;
  else if (strcmp(name, "Vo")==0)
	return 4;
  else if (strcmp(name, "a")==0)
	return 5;
  else if (strcmp(name, "b")==0)
	return 6;
  else if (strcmp(name, "c")==0)
	return 7;
  else if (strcmp(name, "d")==0)
	return 8;
  else if (strcmp(name, "g")==0)
	return 9;
  else if (strcmp(name, "lam")==0)
	return 10;
  else if (strcmp(name, "r")==0)
	return 11;
  else if (strcmp(name, "s")==0)
	return 12;
  else if (strcmp(name, "thet")==0)
	return 13;
  else if (strcmp(name, "x1")==0)
	return 14;
  else {
	fprintf(stderr, "Invalid name %s for getindex call\n", name);
	return 0.0/0.0;
	}
}


double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {return e3_;} else {return temp_;};
}


double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ > e2_) {return e1_;} else {return e2_;};
}


double globalindepvar(double t, double *p_, double *wk_, double *xv_) {
  return globalt0+t;
}


double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {temp_ = e3_;};
if (e4_ > temp_) {return e4_;} else {return temp_;};
}


double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_) {
  return gBds[which_bd][getindex(name, p_, wk_, xv_)];
}


double initcond(char *varname, double *p_, double *wk_, double *xv_) {

  if (strcmp(varname, "x")==0)
	return gICs[0];
  else if (strcmp(varname, "y")==0)
	return gICs[1];
  else if (strcmp(varname, "z")==0)
	return gICs[2];
  else {
	fprintf(stderr, "Invalid variable name %s for initcond call\n", varname);
	return 0.0/0.0;
	}
}


int heav(double x_, double *p_, double *wk_, double *xv_) {
  if (x_>0.0) {return 1;} else {return 0;}
}


double gam(double __x__, double *p_, double *wk_, double *xv_) {


return 1/(1+(pow(2.71828,-1*lam*(__x__-thet))));

}


double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_) {
  if (cond_) {return e1_;} else {return e2_;};
}


double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {return e3_;} else {return temp_;};
}


double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ < e2_) {return e1_;} else {return e2_;};
}


double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {temp_ = e3_;};
if (e4_ < temp_) {return e4_;} else {return temp_;};
}

void auxvars(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){


}


void jacobian(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobianParam(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}
