/*  Vector field and other functions for Auto continuer.
   This code was automatically generated by PyDSTool, but may be modified by hand. */

#include "auto_f2c.h"
#include <stdio.h>
#include "autovfield.h"
#include <math.h>
#include "auto_c.h"
#include <string.h>
#include <stdlib.h>

double *gICs;
double **gBds;
double globalt0;

static double pi = 3.1415926535897931;


/* Variable, parameter, and input definitions: */ 
#define C	p_[0]
#define Iapp	p_[1]
#define gCa	p_[2]
#define gK	p_[3]
#define gL	p_[4]
#define phi	p_[5]
#define v1	p_[6]
#define v2	p_[7]
#define v3	p_[8]
#define v4	p_[9]
#define vCa	p_[50]
#define vK	p_[51]
#define vL	p_[52]
#define _T	p_[10]
#define v	Y_[0]
#define w	Y_[1]


int getindex(char *name, double *p_, double *wk_, double *xv_);
double tau(double __v__, double *p_, double *wk_, double *xv_);
double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double globalindepvar(double t, double *p_, double *wk_, double *xv_);
double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);
double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_);
double minf(double __v__, double *p_, double *wk_, double *xv_);
int heav(double x_, double *p_, double *wk_, double *xv_);
double initcond(char *varname, double *p_, double *wk_, double *xv_);
double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_);
double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_);
double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_);
double winf(double __v__, double *p_, double *wk_, double *xv_);
double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_);

void auxvars(unsigned, unsigned, double, double*, double*, double*, unsigned, double*, unsigned, double*);
void jacobian(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
void jacobianParam(unsigned, unsigned, double, double*, double*, double**, unsigned, double*, unsigned, double*);
int N_AUXVARS = 0;


void vfieldfunc(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){

f_[0] = (Iapp-gCa*minf(v, p_, wk_, xv_)*(v-vCa)-gK*w*(v-vK)-gL*(v-vL))/C;
f_[1] = phi*(winf(v, p_, wk_, xv_)-w)/tau(v, p_, wk_, xv_);

}




int getindex(char *name, double *p_, double *wk_, double *xv_) {

  if (strcmp(name, "v")==0)
	return 0;
  else if (strcmp(name, "w")==0)
	return 1;
  else if (strcmp(name, "C")==0)
	return 2;
  else if (strcmp(name, "Iapp")==0)
	return 3;
  else if (strcmp(name, "gCa")==0)
	return 4;
  else if (strcmp(name, "gK")==0)
	return 5;
  else if (strcmp(name, "gL")==0)
	return 6;
  else if (strcmp(name, "phi")==0)
	return 7;
  else if (strcmp(name, "v1")==0)
	return 8;
  else if (strcmp(name, "v2")==0)
	return 9;
  else if (strcmp(name, "v3")==0)
	return 10;
  else if (strcmp(name, "v4")==0)
	return 11;
  else if (strcmp(name, "vCa")==0)
	return 12;
  else if (strcmp(name, "vK")==0)
	return 13;
  else if (strcmp(name, "vL")==0)
	return 14;
  else {
	fprintf(stderr, "Invalid name %s for getindex call\n", name);
	return 0.0/0.0;
	}
}


double tau(double __v__, double *p_, double *wk_, double *xv_) {


return 1/cosh((__v__-v3)/(2*v4));

}


double __maxof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {return e3_;} else {return temp_;};
}


double __maxof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ > e2_) {return e1_;} else {return e2_;};
}


double globalindepvar(double t, double *p_, double *wk_, double *xv_) {
  return globalt0+t;
}


double __maxof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ > e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ > temp_) {temp_ = e3_;};
if (e4_ > temp_) {return e4_;} else {return temp_;};
}


double getbound(char *name, int which_bd, double *p_, double *wk_, double *xv_) {
  return gBds[which_bd][getindex(name, p_, wk_, xv_)];
}


double minf(double __v__, double *p_, double *wk_, double *xv_) {


return 0.5*(1+tanh((__v__-v1)/v2));

}


int heav(double x_, double *p_, double *wk_, double *xv_) {
  if (x_>0.0) {return 1;} else {return 0;}
}


double initcond(char *varname, double *p_, double *wk_, double *xv_) {

  if (strcmp(varname, "v")==0)
	return gICs[0];
  else if (strcmp(varname, "w")==0)
	return gICs[1];
  else {
	fprintf(stderr, "Invalid variable name %s for initcond call\n", varname);
	return 0.0/0.0;
	}
}


double __rhs_if(int cond_, double e1_, double e2_, double *p_, double *wk_, double *xv_) {
  if (cond_) {return e1_;} else {return e2_;};
}


double __minof3(double e1_, double e2_, double e3_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {return e3_;} else {return temp_;};
}


double __minof2(double e1_, double e2_, double *p_, double *wk_, double *xv_) {
if (e1_ < e2_) {return e1_;} else {return e2_;};
}


double winf(double __v__, double *p_, double *wk_, double *xv_) {


return 0.5*(1+tanh((__v__-v3)/v4));

}


double __minof4(double e1_, double e2_, double e3_, double e4_, double *p_, double *wk_, double *xv_) {
double temp_;
if (e1_ < e2_) {temp_ = e1_;} else {temp_ = e2_;};
if (e3_ < temp_) {temp_ = e3_;};
if (e4_ < temp_) {return e4_;} else {return temp_;};
}

void auxvars(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double *f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_){


}


void jacobian(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}

void jacobianParam(unsigned n_, unsigned np_, double t, double *Y_, double *p_, double **f_, unsigned wkn_, double *wk_, unsigned xvn_, double *xv_) {
}
