#
# hr.py
#
# PyDSTool Python file for the vector field named: hr
#
# This file was generated by the program VFGEN, version: 2.5.0
# Generated on  3-Apr-2017 at 15:19
#

import PyDSTool

#
# args()
#
# This function creates a PyDSTool 'args' object for the
# 'hr' vector field.
#

def args():
    """
    This function creates a PyDSTool 'args' object for the
    'hr' vector field.
    """
    DSargs = PyDSTool.args()
    DSargs.name = 'hr'
    DSargs.pars = {'a':1.0000000000000000e+00, 'b':3.2999999999999998e+00, 'c':1.0000000000000000e+00, 'd':5.0000000000000000e+00, 'r':1.0000000000000000e-03, 's':4.0000000000000000e+00, 'xR':-1.6180339887499999e+00, 'Iapp':2.0000000000000000e+00, 'g':0.0000000000000000e+00, 'Vo':2.0000000000000000e+00, 'lam':1.0000000000000000e+01, 'thet':-5.9999999999999998e-01}
    DSargs.varspecs = {'x':'-a*(x*x*x)+(x*x)*b-z+Iapp+1.0/( pow(2.7182800000000000e+00,-( x-thet)*lam)+1.0)*g*( Vo-x)+y', 'y':' c-(x*x)*d-y', 'z':'r*( s*( x-xR)-z)'}
    DSargs.fnspecs = {'Jacobian': (['t', 'x', 'y', 'z'],
            """[[ 9.9999932734728203e-01*1.0/pow( pow(2.7182800000000000e+00,-( x-thet)*lam)+1.0,2.0)*pow(2.7182800000000000e+00,-( x-thet)*lam)*lam*g*( Vo-x)+-3.0*a*(x*x)-1.0/( pow(2.7182800000000000e+00,-( x-thet)*lam)+1.0)*g+2.0*x*b, 1.0, -1.0],
                [-2.0*x*d, -1.0, 0.0],
                [r*s, 0.0, -r]]""")}
    DSargs.ics = {'x':-1.6180339887499999e+00, 'y':-1.2090169943799999e+01, 'z':2.1499999999999999e+00}
    DSargs.tdomain = [0,1000]
    return DSargs
