#
# hr_dst.py
#
#
# This script uses PyDSTool to plot a solution to the
# differential equations defined in hr.py
#
# This file was generated by the program VFGEN, version: 2.5.0
# Generated on  3-Apr-2017 at 15:19
#

import sys
import matplotlib.pyplot as plt
import PyDSTool
import hr

# Compute the solution
ds = hr.args()
ode = PyDSTool.Generator.Vode_ODEsystem(ds)
traj = ode.compute('traj')
sol = traj.sample(dt=0.05)

# Plot the solution
lw = 1.5
plt.plot(sol['t'], sol['x'], linewidth=lw)
plt.plot(sol['t'], sol['y'], linewidth=lw)
plt.plot(sol['t'], sol['z'], linewidth=lw)
plt.xlabel('t')
plt.title('hr')
plt.legend(('x', 'y', 'z'))
plt.grid(True)

if len(sys.argv) > 1:
    plt.savefig(sys.argv[1], dpi=72)
else:
    plt.show()
